spring:
  config:
    activate:
      on-profile: dev
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:realvista_test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  # JPA Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Cache
  cache:
    type: simple

# Logging
logging:
  level:
    root: INFO
    com.sep.realvista: DEBUG
    org.springframework.security: DEBUG

# Swagger
springdoc:
  swagger-ui:
    enabled: true

